RUN  apt update \
  && apt install -y valgrind clang clang-tools clang-format clang-tidy ccache \
  && rm -rf /var/lib/apt/lists/*

RUN  apt update \
  && apt install -y clang-tools-8 clang-8 clang-tidy-8 libclang-8-dev llvm-8-tools clang-format-8 libclang-8-dev llvm-8-dev llvm-8-runtime llvm-8-examples llvm-8-doc \
  && rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:/usr/lib/llvm-8/bin"

# TODO: update alternatives?