RUN  apt update \
  && apt install -y git libboost-all-dev libprotobuf-dev protobuf-compiler\
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/fpwork/libs
WORKDIR /var/fpwork/libs
RUN git clone https://github.com/google/googletest.git
WORKDIR googletest
RUN mkdir build
WORKDIR build
RUN cmake ..; make install

WORKDIR /


