RUN  apt update \
  && apt install -y autojump git vim \
  && rm -rf /var/lib/apt/lists/*

RUN echo '. /usr/share/autojump/autojump.sh' >> ~/.bashrc
RUN echo '. /usr/share/autojump/autojump.sh' >> ~/.zshrc

# it would be nice to populate history somehow.
