include(Dockerfile.qtc)
include(Dockerfile.cmake)
include(Dockerfile.clang)
include(Dockerfile.gcc)
include(Dockerfile.cpplibs)
include(Dockerfile.zsh)
include(Dockerfile.autojump)
include(Dockerfile.mycode)
