custom_downloads := bazel.sh

bazel.sh:
	$(call download,bazel.sh,https://github.com/bazelbuild/bazel/releases/download/0.24.0/bazel-0.24.0-installer-linux-x86_64.sh)

include ../cuda-gl-qtc/Makefile
